Repository vacation-hard-study/LOL_ITW, pull requests merged in 2022-08, with the labels that each got.

#7 Feature/5 header design
  css/index.css
  index.html
Labels: feat

#8 Develop
  css/index.css
  index.html
Labels: feat

#9 Feature/4 worldcup list
  .github/workflows/submodule_updates.yml
  css/index.css
  img/champion/ash.png
  index.html
Labels: 병합

#12 dynamic generation logic in js
  index.html
  js/index.js
Labels: feat

#17 fix: file location bug
  js/index.js
Labels: fix

#18 Merge Develop to Main
  js/index.js
Labels: fix, 병합
